version: 2

sources:
  - name: retail_raw
    database: RETAIL
    schema: PUBLIC
    tables:
      - name: TRANSACTIONDETAILS
        columns: 
         - name: TRANSACTION_ID
           tests:
            - not_null

